target: RainTomorrow
object_cols:
  - Date
  - Location
  - WindGustDir
  - WindDir9am
  - WindDir3pm
  - RainToday
  - RainTomorrow
wind_cols:
  - WindGustDir
  - WindDir9am
  - WindDir3pm
rain_cols:
  - RainToday
  - RainTomorrow
nan_cols:
  - Evaporation
  - Sunshine
  - Cloud9am
  - Cloud3pm
cols_to_drop:
  - Date
  - Location
  - Temp9am
  - Temp3pm
  - Pressure9am
wind_direction:
  - W
  - N
  - E
  - S
outlier_cols:
  - MinTemp
  - MaxTemp
  - Rainfall
  - Evaporation
  - WindGustSpeed
  - WindSpeed9am
  - WindSpeed3pm
robust_cols:
  - Rainfall
  - Evaporation
min_max_cols:
  - MinTemp
  - MaxTemp
  - Sunshine
  - WindGustSpeed
  - WindSpeed9am
  - WindSpeed3pm
  - Humidity9am
  - Humidity3pm
  - Pressure3pm
  - Cloud9am
  - Cloud3pm

#lin_reg:
#  -
#    n_jobs:
#      - -1

log_reg:
  -
    C:
      - 0.01
      - 0.1
      - 1
      - 5
      - 10
      - 25
      - 50
      - 100
      - 500
      - 1000
  -
    solver:
      - newton-cg
      - lbfgs
      - liblinear

#svm:
#  -
#    kernel:
#      - rbf
#      - poly
#  -
#    C:
#      - 0.1
#      - 1
#      - 5
#      - 10
#      - 50
#  -
#    gamma:
#      - auto
#      - scale

knn:
  -
    n_neighbors:
      - 5
      - 10
      - 20
      - 40
  -
    weights:
      - uniform
      - distance
  -
    metric:
      - euclidean
      - manhattan
      - chebyshev
      - minkowski

decision_tree:
  -
    criterion:
      - gini
      - entropy
  -
    max_depth:
      - 7
      - 10
      - 12
      - 15

random_forest:
  -
    n_estimators:
      - 5
      - 10
      - 20
      - 50
      - 100
  -
    criterion:
      - gini
      - entropy
  -
    max_depth:
      - 5
      - 7
      - 10
      - 12

mlp:
  -
    solver:
      - adam
      - lbfgs
  -
    activation:
      - tanh
      - logistic
      - relu
  -
    alpha:
      - 0.0001
      - 0.001
      - 0.05
      - 0.1

